version: 1
accounts:
  - name: alice
    coins: ["990000000000000000000000aside"]
  - name: bob
    coins: ["10000000000000000000000aside"]
validators:
  - name: alice
    bonded: "10000000000000000000000aside"
client:
  openapi:
    path: "docs/static/openapi.yml"
  typescript:
    path: "ts-client"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["5aside"]
genesis:
  chain_id: side_7070-1
  app_state:
    staking:
      params:
        bond_denom: "aside"