name: Build and Deploy

on:
  push:
    branches:
      - main # or the branch you want to deploy from

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ DedicatedDev }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ DedicatedDev }}/your-image-name:latest

      # - name: Deploy to server
      #   env:
      #     PRIVATE_KEY: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
      #     HOST: ${{ secrets.SERVER_HOST }}
      #     USER: ${{ secrets.SERVER_USER }}
      #   run: |
      #     echo "$PRIVATE_KEY" > private_key.pem
      #     chmod 600 private_key.pem
      #     scp -i private_key.pem -r deployment-scripts/ $USER@$HOST:/path/to/deployment/
      #     ssh -i private_key.pem $USER@$HOST 'bash -s' < /path/to/deployment/deploy.sh
      #     rm -f private_key.pem
